# Generated by Django 4.2.5 on 2023-09-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.department')),
            ],
        ),
    ]
